# Generated by Django 4.2.13 on 2024-06-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housework', '0003_houseinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='avatar',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
