# Generated by Django 4.2.13 on 2024-06-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housework', '0005_rename_avatar_house_imagename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='users',
            new_name='hearthUsers',
        ),
    ]
