# Generated by Django 4.2.13 on 2024-07-04 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housework', '0006_rename_users_house_hearthusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseworkmadetask',
            name='possible_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='housework.houseworkpossibletask'),
        ),
    ]
