# Generated by Django 4.2.13 on 2024-07-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housework', '0008_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='house',
            new_name='hearth',
        ),
        migrations.AddField(
            model_name='score',
            name='involvement',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='score',
            name='corrected_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
